"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PurchasesErrorCode = void 0;
// Error codes indicating the reason for an error.
var PurchasesErrorCode;
(function (PurchasesErrorCode) {
    PurchasesErrorCode["UnknownError"] = "0";
    PurchasesErrorCode["PurchaseCancelledError"] = "1";
    PurchasesErrorCode["StoreProblemError"] = "2";
    PurchasesErrorCode["PurchaseNotAllowedError"] = "3";
    PurchasesErrorCode["PurchaseInvalidError"] = "4";
    PurchasesErrorCode["ProductNotAvailableForPurchaseError"] = "5";
    PurchasesErrorCode["ProductAlreadyPurchasedError"] = "6";
    PurchasesErrorCode["ReceiptAlreadyInUseError"] = "7";
    PurchasesErrorCode["InvalidReceiptError"] = "8";
    PurchasesErrorCode["MissingReceiptFileError"] = "9";
    PurchasesErrorCode["NetworkError"] = "10";
    PurchasesErrorCode["InvalidCredentialsError"] = "11";
    PurchasesErrorCode["UnexpectedBackendResponseError"] = "12";
    PurchasesErrorCode["ReceiptInUseByOtherSubscriberError"] = "13";
    PurchasesErrorCode["InvalidAppUserIdError"] = "14";
    PurchasesErrorCode["OperationAlreadyInProgressError"] = "15";
    PurchasesErrorCode["UnknownBackendError"] = "16";
    PurchasesErrorCode["InvalidAppleSubscriptionKeyError"] = "17";
    PurchasesErrorCode["IneligibleError"] = "18";
    PurchasesErrorCode["InsufficientPermissionsError"] = "19";
    PurchasesErrorCode["PaymentPendingError"] = "20";
    PurchasesErrorCode["InvalidSubscriberAttributesError"] = "21";
    PurchasesErrorCode["LogOutAnonymousUserError"] = "22";
})(PurchasesErrorCode = exports.PurchasesErrorCode || (exports.PurchasesErrorCode = {}));
