require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$deployment_target = '10.0'
platform :ios, $deployment_target

def set_deployment_target_for_all_pods(installer)
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $deployment_target
    end
  end
end

target 'ReactNativeSample' do
  # Pods for ReactNativeSample
  pod 'RNPurchases', :path => '../../../'

  config = use_native_modules!
  
  pod 'Purchases', :git => 'https://github.com/RevenueCat/purchases-ios.git', :branch => 'feature/identityV3_public_facing_changes'
  pod 'PurchasesCoreSwift', :git => 'https://github.com/RevenueCat/purchases-ios.git', :branch => 'feature/identityV3_public_facing_changes'
  pod 'PurchasesHybridCommon', :git => 'https://github.com/RevenueCat/purchases-hybrid-common.git', :branch => 'develop'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    set_deployment_target_for_all_pods(installer)
  end
end
